steps:
  - name: gcr.io/kaniko-project/executor:latest
    id: agent
    args:
      - "--build-arg=$SHORT_SHA"
      - "--destination=europe-west1-docker.pkg.dev/correctify-dev/playground/golang-gin-server:$SHORT_SHA"
      - "--context=."
      - "--cache=true"
      - "--cache-ttl=10s"
  
  # - name: gcr.io/cloud-builders/gcloud
  #   id: tagging
  #   waitFor:
  #     - agent
  #   script: |
  #     gcloud artifacts tags create  --location=europe-west1 


  - name: gcr.io/cloud-builders/gcloud
    waitFor:
      - agent
    script: |
      echo "SHORT_SHA: ${SHORT_SHA}"
      gcloud run deploy --allow-unauthenticated --region=europe-west1 --image="europe-west1-docker.pkg.dev/correctify-dev/playground/golang-gin-server:${SHORT_SHA}" golang-gin-server

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - "europe-west1-docker.pkg.dev/correctify-dev/playground/golang-gin-server"