steps:
  - name: gcr.io/kaniko-project/executor:latest
    id: agent
    args:
      - "--destination=europe-west1-docker.pkg.dev/correctify-dev/playground/golang-gin-server"
      - "--context=."
      - "--cache=true"
      - "--cache-ttl=10s"
  
  - name: gcr.io/cloud-builders/gcloud
    waitFor:
      - agent
    script: |
      gcloud run deploy --allow-unauthenticated --region=europe-west1 --image=europe-west1-docker.pkg.dev/correctify-dev/playground/golang-gin-server golang-gin-server

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - "europe-west1-docker.pkg.dev/correctify-dev/playground/golang-gin-server"