steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    script: |
      gcloud run services update golang-gin-server --image europe-west3-docker.pkg.dev/correctify-dev/playground/golang-gin-server --region europe-west3