steps:
  - name: gcr.io/kaniko-project/executor:latest
    id: agent
    env:
      - "SHORT_SHA=$SHORT_SHA"
    args:
      - "--build-arg SHORT_SHA=$SHORT_SHA"
      - "--destination=europe-west1-docker.pkg.dev/correctify-dev/playground/golang-gin-server:latest"
      - "--context=."
      - "--cache=true"
      - "--cache-ttl=10s"
  
  # - name: gcr.io/cloud-builders/gcloud
  #   id: tagging
  #   waitFor:
  #     - agent
  #   script: |
  #     gcloud artifacts docker tags add  --location=europe-west1 europe-west1-docker.pkg.dev/correctify-dev/playground/golang-gin-server:latest


  - name: gcr.io/cloud-builders/gcloud
    waitFor:
      - agent
    script: |
      gcloud run services update --region=europe-west1 --image=europe-west1-docker.pkg.dev/correctify-dev/playground/golang-gin-server:latest golang-gin-server

options:
  logging: CLOUD_LOGGING_ONLY